### ISSUE TITLE
GUI or Web frontend?

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/alpacascope#11]
Apparently Go has a cross-platform GUI toolkit: https://fyne.io

And of course there are Web Toolkits available: github.com/labstack/echo

**Comment by BobDenny** [comment]
I vote for web. Would this be accessible from SkySafari settings web page??? I am a doofus with SkySafari.  Plus with the right plumbing, the web page would be accesible from elsewhere. And well cross platform UI toolkits can be fussy.

**Comment by synfinatic** [comment]
"SkySafari settings web page"?  I've never seen that??? Can you tell me how?  Then maybe I can figure out if it's possible.  (Honestly, I doubt it, but never know!)

Honestly, I'm much better with webapps than GUI's, but it's also not saying much.  My webui's are notoriously bad.  But it's a simple app with only a few settings so it shouldn't be a big deal.

**Comment by synfinatic** [comment]
Found it in both the iOS and MacOS app.  Looks like it then tries doing http to port 80.  Simple. :)

**Comment by synfinatic** [comment]
<img width="503" alt="AlpacaScopeReady" src="https://user-images.githubusercontent.com/1075352/126832637-c182ac9e-47b9-46b5-b129-4f94380f5a1e.png">

**Comment by synfinatic** [comment]
<img width="630" alt="Screen Shot 2021-07-24 at 5 52 37 PM" src="https://user-images.githubusercontent.com/1075352/126884358-f10c1bc5-770d-459e-a916-69fbfbfdd3eb.png">

**Comment by synfinatic** [comment]
Ended up doing this as a [Fyne](https://fyne.io) application because many people were confused with CLI applications without a GUI.  And most AlpacaScope users are going to be Windows users and everyone wants a GUI.

**Comment by synfinatic** [comment]
smaller version 
<img width="315" alt="Screen Shot 2021-07-24 at 5 52 37 PM" src="https://user-images.githubusercontent.com/1075352/126884700-13caa5e7-fca7-4fc2-8c1e-33dad1ca353d.png">
