### ISSUE TITLE
Tracking commands (T|t) are not supported by ASCOM

### ISSUE THREAD

**Issue by BobDenny** [synfinatic/alpacascope#15]
I may be off on this. Sidereal tracking may be turned on and off via PUT /telescope/{device_number}/tracking, see the [Telescope Specific Methods](https://ascom-standards.org/api/#/Telescope%20Specific%20Methods). Not all mounts support  PUT (turning it on and off). To find out check the value of GET /telescope/{device_number}/cansettracking. 

If you try to slew the scope and sidereal tracking is off, many mounts report that they cannot be slewed to RA/Dec (slewtocoordinatessync).

**Comment by synfinatic** [comment]
Yeah, this is when you're running in NexStar mode... Alpaca/ASCOM seems to support on/off while NexStar supports off and Alt/Az vs EQ North vs EQ South.  As I mentioned on CN, I suppose I could just treat the latter three as an "off" when doing a PUT, but I have no idea how to map things for GET's.  I suppose I could make this an option on the CLI and users could hard code it based on their mount type/location?  

Open to ideas
