### ISSUE TITLE
Missing NexStar Commands:  "J", "h", "P" and "m"

### ISSUE THREAD

**Issue by PaxAndromeda** [synfinatic/alpacascope#57]
There are several unsupported commands that are continuously spamming the CLI.  These commands are emitted by Stellarium Mobile.  It does not seem like Stellarium Mobile is able to sync the telescope or set the location without knowing the alignment state.  Furthermore, Stellarium Mobile will occasionally query the current telescope time.

The two unimplemented commands are:

### "h" - Get Time
This should return the time in the same format as the "H" command handled at https://github.com/synfinatic/alpacascope/blob/main/telescope/nexstar.go#L219

### "J" - Is alignment complete?
Should return `1` if the alignment is complete.  For the sake of compatibility, this should return `1` if the alignment state is unknown.

Details of these commands may be found in the NexStar protocol document found here:  https://s3.amazonaws.com/celestron-site-support-files/support_files/1154108406_nexstarcommprot.pdf

**Comment by synfinatic** [comment]
@YourGirlInSpace If you tell me what binary (OS/hardware) you'd like, I'll build you a binary to test.

**Comment by PaxAndromeda** [comment]
> @YourGirlInSpace If you tell me what binary (OS/hardware) you'd like, I'll build you a binary to test.

I am running Windows 10 Pro, 64 bit.  I can test this evening.  Thanks!

**Comment by synfinatic** [comment]
~~Here ya go: [alpacascope.zip](https://github.com/synfinatic/alpacascope/files/9491505/alpacascope.zip)~~

**Comment by synfinatic** [comment]
Small code tweak which should fix a bug I discovered: 
[AlpacaScope-Debug-2.4.0.exe.zip](https://github.com/synfinatic/alpacascope/files/9491841/AlpacaScope-Debug-2.4.0.exe.zip)

**Comment by PaxAndromeda** [comment]
Awesome, I will test this later tonight and get back too you with further information.  Thanks @synfinatic !

**Comment by PaxAndromeda** [comment]
I was able to test the server and it still exhibits the same issue as far as I can tell.  If possible, a console build would be more helpful for the sake of debugging, or a method to retrieve logs from the UI version.

**Comment by synfinatic** [comment]
CLI version: [alpacascope-cli.zip](https://github.com/synfinatic/alpacascope/files/9492118/alpacascope-cli.zip)

**Comment by PaxAndromeda** [comment]
```
ERRO[0044] Unable to get date from scope: parsing time "" as "2006-01-02T15:04:05Z0700": cannot parse "" as "2006"
ERRO[0044] command 'h☺��   ☻                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ' returned a zero length reply
```

I output the data to the attached file.
[output.bin.zip](https://github.com/synfinatic/alpacascope/files/9492174/output.bin.zip)

**Comment by synfinatic** [comment]
huh... I guess your scope doesn't support that call?  I'm curious what scope/mount you have?

Anyways, this I think should fix it???  
[alpacascope-cli.zip](https://github.com/synfinatic/alpacascope/files/9492290/alpacascope-cli.zip)

**Comment by PaxAndromeda** [comment]
In particular, I am using an Orion Sirius EQ-G using [EQMod](http://eq-mod.sourceforge.net/) / [EQAscom](http://eq-mod.sourceforge.net/eqaindex.html)

This change does 'fix' it, but now the time shows as Incorrect and the location does not sync.  Perhaps in the case of the mount not returning the time, or the time option being unavailable, it should be assumed to match the server's system time.

**Comment by synfinatic** [comment]
I'll have to dig in deeper then... later this week.

Also, if Stellarium supports the LX200 protocol, you can try that.    Not sure if the issue is on the Alpaca or NexStar side of things at the moment.

**Comment by PaxAndromeda** [comment]
I did attempt to use the LX200 protocol, but there is an entirely separate issue that crops up:

```
INFO[0000] Looking for Alpaca Remote Server locally on port 11111...
INFO[0003] Found Alpaca on 192.168.30.17:11111
INFO[0003] Starting SkyFi Discovery service on UDP/4031
INFO[0003] Connected to telescope 0:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/synfinatic/alpacascope/alpaca.(*Telescope).GetAxisRates(0xc0000920c0, 0x0?)
        /Users/aturner/go/src/github.com/synfinatic/alpacascope/alpaca/telescope.go:179 +0x4e5
main.main()
        /Users/aturner/go/src/github.com/synfinatic/alpacascope/cmd/main.go:187 +0xfe5
```

If necessary, I can open a new issue about this as well.

**Comment by synfinatic** [comment]
So the error with the index out of range/length zero is basically a driver issue:

https://ascomtalk.groups.io/g/Developer/message/5718

Basically, the driver is not returning meaningful data.  Clearly, my code shouldn't crash in this situation, but there doesn't seem to be a graceful solution when the client (Stellarium) later wants to call MoveAxis which requires a rate.  It won't know what rates are valid.

At this point I would contact the EQmod driver and see what is up?

**Comment by PaxAndromeda** [comment]
Regarding the axis, I do notice this when initializing as a Nexstar server:

```
ERRO[0234] Unknown direction: 254
ERRO[0239] Unknown direction: 254
ERRO[0244] Unknown axis: 176
ERRO[0244] Unknown direction: 254
```

`Unknown axis: 176 (0xB0)`

Now this is interesting, because this isn't an axis.  `176` in a 'P' command refers to the GPS command `P` "Is GPS Linked?".  This occurs when Stellarium is looking for the current location of the telescope.  GPS, however, is not supported in ASCOM.

Additionally, `Unknown direction: 254` refers to the `P` command "Get Device Version", also noted in the documentation.  In the absence of this command, Stellarium assumes device `176`, which is a GPS Unit.  This should return `16` (AZM/RA) or `17` (ALT/DEC), unless you intend to add GPS support to this software in the future.

**Comment by PaxAndromeda** [comment]
Were you able to confirm this in your testing, @synfinatic ?

**Comment by synfinatic** [comment]
Sorry, been out of town and haven't had a chance to look at this further.  Does look like Stellerium mobile on iOS will let me play with this for 7 days for free, so I plan on doing that.

**Comment by synfinatic** [comment]
On page 4 of the NexStar spec:

> **Note:** The Get commands do not retrieve the time and location from the GPS unit (if one is present). The time and    location are retrieved from the hand control. You must first enter the View Time/Site menu to update the hand control time if you want the time from the GPS or, use the GPS Commands in the next section.

So just checking that you set the time & location in the hand controller before trying to connect?  That might explain why you're seeing an empty response for the time.

**Comment by PaxAndromeda** [comment]
Yes, the time and date are set in EQMod and are presenting normally.  Your code does not handle these packets, as described above.

Ref this code:
https://github.com/synfinatic/alpacascope/blob/1631cf0947c62b8ec3194670d546f3d092027fc5/telescope/nexstar.go#L288-L306

**Comment by synfinatic** [comment]
Sorry, I should been more clear.  I was referring to this comment/error message: https://github.com/synfinatic/alpacascope/issues/57#issuecomment-1237497576

The "fixed" code was just a hack and returns the current computer time, not mount time.

**Comment by PaxAndromeda** [comment]
Sorry Aaron!  Mea culpa.  EQMod does support time and does return it in its call (NINA confirms this).

**Comment by synfinatic** [comment]
Welp, this works for me using the ASCOM telescope simulator w/ Stellarium Mobile.  Mind giving it a try? [alpacascope.zip](https://github.com/synfinatic/alpacascope/files/9603800/alpacascope.zip)

**Comment by PaxAndromeda** [comment]
Hi Aaron,

Looks like the alignment indication does work now, but the time is not set.  The output of the CLI is:  [output.txt](https://github.com/synfinatic/alpacascope/files/9603872/output.txt)
I suspect in this case, it may be best to mock the result and set to the computer's local time.

I was also able to identify another small issue, where it does not display the location from the telescope, but is somehow able to set it.  As indicated in the Stellarium logs below, it returns a sequence of 8 zeros.

```
L => 0#
W/(*[0]z[11][8][1] => #
Successfully set telescope location
//....
w => [0][0][0][0][0][0][0][0]#
```

# Startup Routine
The full startup routine from Stellarium's perspective was:

```
Starting telescope connection on Network
Host: [redacted] Port: 4030
Serial link status changed: connecting
Serial link status changed: connected
Identifying telescope controller...
Trying NexStar...
Ka => a#
Detected a NexStar-compatible controller
V => 50#
P[1][16][254][0][0][0][2] => [5][0]#
P[1][17][254][0][0][0][2] => [5][0]#
P[1][176][254][0][0][0][2] => [1][6]#
m => [12]#
w => [0][0][0][0][0][0][0][0]#
h => TRX timeout
Could not get all telescope info: TRX timeout
Continue in degraded mode
Identified telescope info: {"mount":{"hc":{"protocol_name":"NexStar","firmware":{"version":"53.48"},"location":{"lng":"0.0000","lat":"0.0000"},"time":{},"protocol_version":3485696},"azm_ra_motor":{"firmware":{"version":"5.0"}},"alt_dec_motor":{"firmware":{"version":"5.0"}},"gps":{"firmware":{"version":"1.6"}},"slewing":false,"aligned":true,"tracking":false}}
```
_note: Stellarium encodes the logs as `SentPacket => ReceivedPacket`_

Of particular note are a few things:  `location`, which reads 0°N 0°E.  EQMOD does output its location per ASCOM specifications, as evidenced in NINA.  I suspect an issue in the `w` command.

Next is the time.  EQMod uses system local time and does expose it as an ASCOM output.

Third is the `"tracking"` field in the JSON that Stellarium provides:  EQMod does indeed show as tracking.  I am unsure why this is reading as false.

Please refer to the screenshot below for the current state of my mount at the time Stellarium started to connect.  It shows EQMod and NINA, which is connected through ASCOM.  It should answer any questions about what data is being sent from EQMod.

![mstsc_2022-09-19_21-12-28](https://user-images.githubusercontent.com/72631462/191166044-b222fb9f-7ec3-4d47-bcbd-111eb60879dd.png)

I hope this is enough information!  :)

**Comment by PaxAndromeda** [comment]
As some additional information, I am able to query Alpaca's API to test some relevant endpoints.  Here is some data for your perusal:

### GET /telescope/0/utcdate
```json
curl -X GET "http://127.0.0.1:11111/api/v1/telescope/0/utcdate?ClientID=1&ClientTransactionID=1234" -H "accept: application/json"

{
    "Value": "2022-09-20T04:18:33",
    "ClientTransactionID": 0,
    "ServerTransactionID": 3,
    "ErrorNumber": 0,
    "ErrorMessage": ""
}
```

### PUT /telescope/0/utcdate
```json
curl -X PUT "http://127.0.0.1:11111/api/v1/telescope/0/utcdate" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "UTCDate=2022-04-01T05%3A00%3A00&ClientID=241&ClientTransactionID=6316"

{
    "ClientTransactionID": 6316,
    "ServerTransactionID": 4,
    "ErrorNumber": 1024,
    "ErrorMessage": "Property UTCDate is not implemented by this telescope driver object."
}
```
_This indicates that setting the date is not possible on EQMod_

### GET /telescope/0/sitelatitude
```json
curl -X GET "http://127.0.0.1:11111/api/v1/telescope/0/sitelatitude?ClientID=1&ClientTransactionID=1234" -H "accept: application/json"

{
    "Value": 47.[REDACTED],
    "ClientTransactionID": 1234,
    "ServerTransactionID": 6,
    "ErrorNumber": 0,
    "ErrorMessage": ""
}
```

### PUT /telescope/0/sitelatitude
```json
curl -X PUT "http://127.0.0.1:11111/api/v1/telescope/0/sitelatitude" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "SiteLatitude=47&ClientID=246&ClientTransactionID=235124"

{
    "ClientTransactionID": 235124,
    "ServerTransactionID": 7,
    "ErrorNumber": 0,
    "ErrorMessage": ""
}
```
_Indicates a successful transaction, afterwards when GETting the site latitude, the following is returned:_
```json
curl -X GET "http://127.0.0.1:11111/api/v1/telescope/0/sitelatitude?ClientID=1&ClientTransactionID=1234" -H "accept: application/json"

{
    "Value": 47.0,
    "ClientTransactionID": 1234,
    "ServerTransactionID": 8,
    "ErrorNumber": 0,
    "ErrorMessage": ""
}
```

**Comment by synfinatic** [comment]
So I've got some theories of what is going on, but figured it was better to collect some data.  

[alpacascope.zip](https://github.com/synfinatic/alpacascope/files/9609372/alpacascope.zip)

This build mostly just improves debugging output which you can enable with the `--debug` flag.  Just a warning it is very verbose, so redirecting the output to a file would probably be best.

**Comment by PaxAndromeda** [comment]
[output.txt](https://github.com/synfinatic/alpacascope/files/9609714/output.txt)

Here you go!  I have redacted any sensitive information.

**Comment by synfinatic** [comment]
So I was expecting to see some zero values/empty strings for replies from ASCOM Remote, but this was far more extensive than I imagined.

Looks like ASCOM Remote is returning all zeros/empty strings- for everything.  There is a bug where AlpacaScope isn't detecting this and aborting, but this seems to explain what we're seeing.

If you have full logging enabled in the ASCOM Remote server, you should see an error along the lines of "Device telescope/0 is not configured on the Remote Server"

When ASCOM Remote is correctly configured, you should see in white text w/ green background both:

`Remote Server Up`
`Drivers Connected`

When I have `Drivers Unloaded` for the second box, I can reproduce this situation.

If you haven't yet, it might be helpful to read [Configure.md](https://github.com/synfinatic/alpacascope/blob/main/Configure.md)

**Comment by synfinatic** [comment]
Fixes the failure to detect the above misconfiguration: [alpacascope.zip](https://github.com/synfinatic/alpacascope/files/9618315/alpacascope.zip)

**Comment by PaxAndromeda** [comment]
Hi @synfinatic, I'm not sold that this is the issue.  As described in https://github.com/synfinatic/alpacascope/issues/57#issuecomment-1251821283, Alpaca _is_ online and the API _is_ responding with information correctly.  Alpaca is configured exactly as you indicated in [Configure.md](https://github.com/synfinatic/alpacascope/blob/main/Configure.md).

However, I _do_ notice that when I ran queries on Alpaca manually, I was able to see all of the `GET` and `PUT` requests.  However, I do not see the same from Alpacascope.

**Comment by PaxAndromeda** [comment]
Hang on.  I just had a thought.  I reconfigured the server to _not_ respond on localhost but respond to the local network IP as well (192.168.*.*).  Now things are working perfectly.  I noticed this after this log message in Alpacascope:

```
INFO[0003] Found Alpaca on 192.168.30.17:11111
```

It seems like Alpacascope isn't actually attempting to connect to Alpaca on 127.0.0.1 at all. but rather the network IP.  Once I adjusted Alpaca to accept this connection, everything works perfectly from what I can tell.

It's always the issues that hide in plain sight :)

**Comment by synfinatic** [comment]
It just searches the list of local IP's (which you redacted) and the first interface that is listening on port 11111 is selected.  If you want to force a specific interface, you can do so via the `--alpaca-host` flag.

**Comment by synfinatic** [comment]
Hey Jessica, just circling back and checking to see if all is good now?

**Comment by PaxAndromeda** [comment]
Hi Aaron, everything seems to be working fine now.  Thank you so much for all your help!  😊
